[package]
name = "vulkan_tests"
version = "0.1.0"
authors = ["Anton Vladimirov <styleex@inbox.ru>"]
edition = "2018"
publish = false

[dependencies]
vulkano = "0.24"
vulkano-shaders = "0.24"
vulkano-win = "0.24"
cgmath = "0.18"
time = "0.2"
winit = "0.25"
png = "0.16"
genmesh = "0.6.2"
