[package]
name = "vulkan_tests"
version = "0.1.0"
authors = ["Anton Vladimirov <styleex@inbox.ru>"]
edition = "2018"
publish = false

[dependencies]
vulkano = "0.17"
vulkano-shaders = "0.17"
vulkano-win = "0.17"
cgmath = "0.17"
png = "0.15.0"
time = "0.1.38"
winit = "0.21"
